"""Hybrid integration tests: Mock Model -> Real Tool execution.

Verifies that tool calls generated by a mocked inference provider
are correctly executed by the real tool system.
"""
import json
import unittest
from pathlib import Path

from tests.helpers import BaseTestCase, MockE2EProvider
from inference.engine import FinishedToolCall
from inference.registry import registry


class TestHybridFlow(BaseTestCase):

    async def test_mock_model_triggers_real_shell_command(self):
        """Mock issues run_shell_command -> real subprocess executes it."""
        registry.register(
            "mock_shell",
            "Mock Shell",
            "",
            MockE2EProvider(stream=[
                (None, FinishedToolCall(
                    name="run_shell_command",
                    parameters=json.dumps({"command": "echo hello-world"}),
                )),
            ]),
        )

        resp = await self.client.post("/api/conversations/prompt", json={
            "agent_id": None,
            "provider_key": "mock_shell",
            "model_id": "m",
            "prompt": "run a command",
        })
        self.assertEqual(resp.status_code, 200)

        conv_id = int(resp.headers["x-conversation-id"])
        conv = (await self.client.get(f"/api/conversations/{conv_id}")).json()

        tool_calls = [m for m in conv["messages"] if m["element"]["type"] == "tool_call"]
        self.assertGreaterEqual(len(tool_calls), 1)

        result = json.loads(tool_calls[-1]["element"]["result"])
        self.assertEqual(result["returncode"], 0)
        self.assertIn("hello-world", result["stdout"])

    async def test_mock_model_parameter_passing(self):
        """Verify mock parameters are correctly passed to the real tool."""
        registry.register(
            "mock_param",
            "Mock Param",
            "",
            MockE2EProvider(stream=[
                (None, FinishedToolCall(
                    name="run_shell_command",
                    parameters=json.dumps({"command": "echo arg1 arg2"}),
                )),
            ]),
        )

        resp = await self.client.post("/api/conversations/prompt", json={
            "agent_id": None,
            "provider_key": "mock_param",
            "model_id": "m",
            "prompt": "do it",
        })
        self.assertEqual(resp.status_code, 200)

        conv_id = int(resp.headers["x-conversation-id"])
        conv = (await self.client.get(f"/api/conversations/{conv_id}")).json()

        tool_calls = [m for m in conv["messages"] if m["element"]["type"] == "tool_call"]
        result = json.loads(tool_calls[-1]["element"]["result"])
        self.assertEqual(result["stdout"].strip(), "arg1 arg2")

    async def test_mock_model_triggers_propose_replace(self):
        """Mock issues propose_replace -> system generates a real proposal."""
        repo_name = "test_replace_hybrid"
        await self.client.post("/api/repositories", json={
            "display_name": "Test Replace Hybrid",
            "internal_name": repo_name,
            "path": self._repo_dir.name,
            "security": "write",
        })

        source_rel = "source.txt"
        Path(self._workspace_dir.name, source_rel).write_text("new content", encoding="utf-8")
        Path(self._repo_dir.name, "target.txt").write_text("old content", encoding="utf-8")

        registry.register(
            "mock_replace",
            "Mock Replace",
            "",
            MockE2EProvider(stream=[
                (None, FinishedToolCall(
                    name="propose_replace",
                    parameters=json.dumps({
                        "target": f"/repositories/{repo_name}/target.txt",
                        "source": f"/workspace/{source_rel}",
                    }),
                )),
            ]),
        )

        resp = await self.client.post("/api/conversations/prompt", json={
            "agent_id": None,
            "provider_key": "mock_replace",
            "model_id": "m",
            "prompt": "replace the file",
        })
        self.assertEqual(resp.status_code, 200)

        conv_id = int(resp.headers["x-conversation-id"])
        conv = (await self.client.get(f"/api/conversations/{conv_id}")).json()

        tool_calls = [m for m in conv["messages"] if m["element"]["type"] == "tool_call"]
        self.assertGreaterEqual(len(tool_calls), 1)

        result = json.loads(tool_calls[-1]["element"]["result"])
        self.assertEqual(result["type"], "replace_proposal")
        self.assertEqual(result["status"], "pending")
        self.assertTrue(tool_calls[-1]["element"]["is_blocking"])


if __name__ == "__main__":
    unittest.main()